#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 jvmName
  exit
 fi
java -ea -cp "${classpath}:../jars/*" -Djava.security.manager \
	 -Djava.security.policy=dcvm.policy \
	 fr.upmc.datacenterclient.basic_admissionController.TestDistributedAdmisionController $1 config.xml
